/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Authorization, AuthorizationInterface } from "../Authorization";

const _abi = [
  {
    inputs: [],
    name: "PROJECT",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "adminRouter",
    outputs: [
      {
        internalType: "contract IAdminProjectRouter",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_adminRouter",
        type: "address",
      },
    ],
    name: "setAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Authorization__factory {
  static readonly abi = _abi;
  static createInterface(): AuthorizationInterface {
    return new utils.Interface(_abi) as AuthorizationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Authorization {
    return new Contract(address, _abi, signerOrProvider) as Authorization;
  }
}
