/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TimeCounterInterface extends ethers.utils.Interface {
  functions: {
    "_grantPermission(address)": FunctionFragment;
    "_revokePermission(address)": FunctionFragment;
    "counterRights(address)": FunctionFragment;
    "getElapsedTimeOf(address)": FunctionFragment;
    "lastActions(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "stampLastAction(address)": FunctionFragment;
    "startTime()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_grantPermission",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_revokePermission",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "counterRights",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getElapsedTimeOf",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "lastActions", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stampLastAction",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_grantPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_revokePermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "counterRights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElapsedTimeOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stampLastAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "CounterRightChanged(address,uint256)": EventFragment;
    "LastActionStamped(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CounterRightChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LastActionStamped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type CounterRightChangedEvent = TypedEvent<
  [string, BigNumber] & { counter: string; right: BigNumber }
>;

export type LastActionStampedEvent = TypedEvent<
  [string, BigNumber] & { actor: string; timestamp: BigNumber }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class TimeCounter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TimeCounterInterface;

  functions: {
    _grantPermission(
      counter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _revokePermission(
      counter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    counterRights(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getElapsedTimeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lastActions(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stampLastAction(
      actor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _grantPermission(
    counter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _revokePermission(
    counter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  counterRights(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getElapsedTimeOf(
    actor: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastActions(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stampLastAction(
    actor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startTime(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _grantPermission(counter: string, overrides?: CallOverrides): Promise<void>;

    _revokePermission(
      counter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    counterRights(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getElapsedTimeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastActions(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    stampLastAction(actor: string, overrides?: CallOverrides): Promise<void>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CounterRightChanged(address,uint256)"(
      counter?: null,
      right?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { counter: string; right: BigNumber }
    >;

    CounterRightChanged(
      counter?: null,
      right?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { counter: string; right: BigNumber }
    >;

    "LastActionStamped(address,uint256)"(
      actor?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { actor: string; timestamp: BigNumber }
    >;

    LastActionStamped(
      actor?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { actor: string; timestamp: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    _grantPermission(
      counter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _revokePermission(
      counter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    counterRights(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getElapsedTimeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastActions(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stampLastAction(
      actor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _grantPermission(
      counter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _revokePermission(
      counter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    counterRights(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getElapsedTimeOf(
      actor: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastActions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stampLastAction(
      actor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
